# Base our container on Rocky Linux since it's RHEL like but open-source
FROM rockylinux:9.3

# TODO: figure out how to install different kernel-headers versions
RUN yum install kernel-headers

# Set $PS1 so we know it's a docker
RUN echo 'export PS1="[\u@rhel_container] \W # "' >> /root/.bashrc

SHELL ["/bin/bash", "-l", "-c"]

